import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"
    case japanese = "ja"
    case korean = "ko"
    case spanish = "es"

    var id: String { rawValue }
    var localeIdentifier: String { rawValue }
    var displayName: String {
        switch self {
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        case .japanese: "日本語"
        case .korean: "한국어"
        case .spanish: "Español"
        }
    }

    func text(_ key: String) -> String {
        if self == .simplifiedChinese { return key }
        return Self.translations[rawValue]?[key] ?? Self.translations[AppLanguage.english.rawValue]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "待机": "Idle", "文字输入": "Text input", "语音输入": "Voice input", "正在预检": "Checking",
            "正在生成": "Generating", "正在下载": "Downloading", "正在写入": "Inserting", "生成完成": "Completed", "任务失败": "Failed",
            "已选择": "Selected", "未选择": "Not selected", "为这一刻配乐": "Score this moment", "正在聆听 · 再次点击麦克风结束": "Listening · click the microphone again to stop",
            "未连接达芬奇": "Resolve disconnected", "已连接达芬奇": "Resolve connected", "设置": "Settings", "音乐时长": "Duration",
            "跟随 In-Out": "Follow In-Out", "自定义": "Custom", "秒": "sec", "音乐时长滑杆": "Duration slider", "风格选择": "Style",
            "随机风格": "Random style", "换一版描述 · 本地随机，无需联网": "Try another local variation", "换一版音乐描述": "Try another description",
            "输入方式": "Input", "音乐描述": "Music brief", "文稿配乐": "Script scoring", "粘贴解说词、故事梗概或分镜，分析后转成配乐描述…": "Paste narration, a synopsis, or a shot list to create a music brief…",
            "结束输入": "Stop input", "分析中…": "Analyzing…", "分析文稿": "Analyze script", "优化描述": "Refine brief", "配乐描述 · 可编辑": "Music brief · editable",
            "文字分析会发送至 TokenHub LLM，并按模型用量计费。": "Text analysis is sent to the TokenHub LLM and billed by model usage.", "历史与恢复": "History & recovery",
            "正在处理…": "Processing…", "生成并放入时间线": "Generate and add to timeline", "1 首": "1 track", "音乐按首计费。生成后裁切匹配选区，备选默认静音。": "Music is billed per track. Output is trimmed to the range; alternates are muted by default.",
            "恢复下载": "Resume download", "插入已下载音频": "Insert downloaded audio", "未连接时间线": "No timeline", "读取最新时间线": "Refresh timeline", "请打开 Resolve 项目": "Open a Resolve project",
            "目标轨道": "Target track", "主版本": "Main", "备选": "Alternate", "放置位置": "Placement", "前 10 秒": "10 sec earlier", "In-Out 起点": "In-Out start", "当前点": "Playhead", "后 10 秒": "10 sec later",
            "定位": "Locate", "采用备选": "Use alternate", "连接、模型与交互权限": "Connection, model, and interaction permissions", "完成": "Done",
            "界面语言": "Interface language", "选择界面显示语言，修改后立即生效。": "Choose the interface language. Changes take effect immediately.", "TokenHub 密钥已保存": "TokenHub key saved", "连接 TokenHub": "Connect TokenHub",
            "粘贴 TokenHub sk-…": "Paste TokenHub sk-…", "保存到钥匙串": "Save to Keychain", "文稿分析模型": "Script analysis model", "模型 ID": "Model ID",
            "填写 TokenHub 的 model 参数值（如 hy3 或 minimax-m3；不要填 minimax）。请单独开通该语言模型的按量服务。": "Enter the TokenHub model value (such as hy3 or minimax-m3; do not use minimax). Enable pay-as-you-go for that language model separately.",
            "交互权限": "Interaction permissions", "启用中键双击 / 重新检查权限": "Enable middle-click shortcut / Recheck permissions",
            "中键双击仅在 Resolve 前台生效。红色退出应用、黄色最小化、绿色或品牌标志切换迷你窗；迷你窗双击恢复完整界面。": "Middle-button double-click works only when Resolve is active. Red quits, yellow minimizes, and green or the brand mark toggles the mini window; double-click the mini window to restore.",
            "首次在 Resolve 中将主轨设为紫色、备选轨设为蓝色。语音输入使用设备端中文识别，点击麦克风时请求权限。": "In Resolve, set the main track to purple and the alternate to blue once. Voice input uses on-device recognition and requests permission when you click the microphone.",
            "TokenHub 在线推理服务": "TokenHub online inference", "保留可执行的恢复入口": "Recover previous usable versions", "还没有生成记录。": "No generation history yet.", "恢复时间线：": "Timeline backup: ", "显示文件": "Show file", "重新采用": "Use again",
            "选择空闲音轨": "Choose free audio tracks", "使用": "Use", "取消": "Cancel", "切换迷你控制窗": "Toggle mini window", "为这一刻配乐。": "Score this moment.",
            "A3/A4 不可用，或当前工作区位于其他轨道。将使用新的连续空轨。": "A3/A4 are unavailable or this workspace uses other tracks. A new consecutive empty pair will be used.",
            "打开 Resolve 时间线，开始创作。": "Open a Resolve timeline to begin.", "已连接": "Connected", "密钥已保存到 macOS 钥匙串。": "The key was saved to macOS Keychain.",
            "雄壮升旗": "Ceremonial Rise", "温暖叙事": "Warm Narrative", "悬疑张力": "Suspense", "科技律动": "Tech Pulse", "史诗磅礴": "Epic", "清新自然": "Fresh Nature", "古风国韵": "Chinese Classical", "轻快活力": "Bright Energy", "沉静冥想": "Calm Meditation", "爵士都市": "Urban Jazz"
        ],
        "zh-Hant": [
            "待机": "待機", "文字输入": "文字輸入", "语音输入": "語音輸入", "正在预检": "正在預檢", "正在生成": "正在生成", "正在下载": "正在下載", "正在写入": "正在寫入", "生成完成": "生成完成", "任务失败": "任務失敗",
            "已选择": "已選擇", "未选择": "未選擇", "为这一刻配乐": "為這一刻配樂", "正在聆听 · 再次点击麦克风结束": "正在聆聽 · 再次點擊麥克風結束", "未连接达芬奇": "未連接達芬奇", "已连接达芬奇": "已連接達芬奇", "设置": "設定", "音乐时长": "音樂時長", "跟随 In-Out": "跟隨 In-Out", "自定义": "自訂", "秒": "秒", "音乐时长滑杆": "音樂時長滑桿", "风格选择": "風格選擇", "随机风格": "隨機風格", "输入方式": "輸入方式", "音乐描述": "音樂描述", "文稿配乐": "文稿配樂", "结束输入": "結束輸入", "分析中…": "分析中…", "分析文稿": "分析文稿", "优化描述": "優化描述", "配乐描述 · 可编辑": "配樂描述 · 可編輯", "历史与恢复": "歷史與恢復", "正在处理…": "正在處理…", "生成并放入时间线": "生成並放入時間線", "1 首": "1 首", "恢复下载": "恢復下載", "插入已下载音频": "插入已下載音訊", "未连接时间线": "未連接時間線", "读取最新时间线": "讀取最新時間線", "请打开 Resolve 项目": "請開啟 Resolve 專案", "目标轨道": "目標軌道", "主版本": "主版本", "备选": "備選", "放置位置": "放置位置", "前 10 秒": "前 10 秒", "In-Out 起点": "In-Out 起點", "当前点": "目前點", "后 10 秒": "後 10 秒", "定位": "定位", "采用备选": "採用備選", "连接、模型与交互权限": "連接、模型與互動權限", "完成": "完成", "界面语言": "介面語言", "选择界面显示语言，修改后立即生效。": "選擇介面顯示語言，修改後立即生效。", "TokenHub 密钥已保存": "TokenHub 金鑰已儲存", "连接 TokenHub": "連接 TokenHub", "粘贴 TokenHub sk-…": "貼上 TokenHub sk-…", "保存到钥匙串": "儲存到鑰匙圈", "文稿分析模型": "文稿分析模型", "模型 ID": "模型 ID", "交互权限": "互動權限", "启用中键双击 / 重新检查权限": "啟用中鍵雙擊 / 重新檢查權限", "TokenHub 在线推理服务": "TokenHub 線上推理服務", "保留可执行的恢复入口": "保留可執行的恢復入口", "还没有生成记录。": "還沒有生成記錄。", "恢复时间线：": "恢復時間線：", "显示文件": "顯示檔案", "重新采用": "重新採用", "选择空闲音轨": "選擇空閒音軌", "使用": "使用", "取消": "取消", "切换迷你控制窗": "切換迷你控制窗",
            "换一版描述 · 本地随机，无需联网": "換一版描述 · 本機隨機，無需連線", "换一版音乐描述": "換一版音樂描述", "粘贴解说词、故事梗概或分镜，分析后转成配乐描述…": "貼上旁白、故事梗概或分鏡，分析後轉為配樂描述…", "文字分析会发送至 TokenHub LLM，并按模型用量计费。": "文字分析會傳送至 TokenHub LLM，並按模型用量計費。", "音乐按首计费。生成后裁切匹配选区，备选默认静音。": "音樂按首計費。生成後裁切匹配選區，備選預設靜音。", "填写 TokenHub 的 model 参数值（如 hy3 或 minimax-m3；不要填 minimax）。请单独开通该语言模型的按量服务。": "填寫 TokenHub 的 model 參數值（如 hy3 或 minimax-m3；不要填 minimax）。請另行開通該語言模型的按量服務。", "中键双击仅在 Resolve 前台生效。红色退出应用、黄色最小化、绿色或品牌标志切换迷你窗；迷你窗双击恢复完整界面。": "中鍵雙擊僅在 Resolve 位於前景時生效。紅色退出、黃色最小化、綠色或品牌標誌切換迷你窗；雙擊迷你窗可恢復完整介面。", "首次在 Resolve 中将主轨设为紫色、备选轨设为蓝色。语音输入使用设备端中文识别，点击麦克风时请求权限。": "首次在 Resolve 中將主軌設為紫色、備選軌設為藍色。語音輸入使用裝置端中文辨識，點擊麥克風時要求權限。", "A3/A4 不可用，或当前工作区位于其他轨道。将使用新的连续空轨。": "A3/A4 無法使用，或目前工作區位於其他軌道。將使用新的連續空軌。", "为这一刻配乐。": "為這一刻配樂。", "打开 Resolve 时间线，开始创作。": "開啟 Resolve 時間線，開始創作。", "已连接": "已連接", "密钥已保存到 macOS 钥匙串。": "金鑰已儲存至 macOS 鑰匙圈。",
            "雄壮升旗": "雄壯升旗", "温暖叙事": "溫暖敘事", "悬疑张力": "懸疑張力", "科技律动": "科技律動", "史诗磅礴": "史詩磅礴", "清新自然": "清新自然", "古风国韵": "古風國韻", "轻快活力": "輕快活力", "沉静冥想": "沉靜冥想", "爵士都市": "爵士都市"
        ],
        "ja": [
            "待机": "待機", "文字输入": "テキスト入力", "语音输入": "音声入力", "正在预检": "確認中", "正在生成": "生成中", "正在下载": "ダウンロード中", "正在写入": "挿入中", "生成完成": "完了", "任务失败": "失敗", "已选择": "選択済み", "未选择": "未選択", "为这一刻配乐": "この瞬間に音楽を", "正在聆听 · 再次点击麦克风结束": "聞き取り中 · もう一度クリックして終了", "未连接达芬奇": "Resolve 未接続", "已连接达芬奇": "Resolve 接続済み", "设置": "設定", "音乐时长": "長さ", "跟随 In-Out": "In-Out に合わせる", "自定义": "カスタム", "秒": "秒", "音乐时长滑杆": "音楽の長さ", "风格选择": "スタイル", "随机风格": "ランダム", "输入方式": "入力", "音乐描述": "音楽の説明", "文稿配乐": "台本から作曲", "结束输入": "入力終了", "分析中…": "分析中…", "分析文稿": "台本を分析", "优化描述": "説明を改善", "配乐描述 · 可编辑": "音楽の説明 · 編集可能", "历史与恢复": "履歴と復元", "正在处理…": "処理中…", "生成并放入时间线": "生成してタイムラインへ", "1 首": "1 曲", "恢复下载": "ダウンロード再開", "插入已下载音频": "音声を挿入", "未连接时间线": "タイムライン未接続", "读取最新时间线": "タイムラインを更新", "请打开 Resolve 项目": "Resolve プロジェクトを開いてください", "目标轨道": "対象トラック", "主版本": "メイン", "备选": "別案", "放置位置": "配置位置", "前 10 秒": "10 秒前", "In-Out 起点": "In-Out 開始", "当前点": "再生ヘッド", "后 10 秒": "10 秒後", "定位": "移動", "采用备选": "別案を採用", "连接、模型与交互权限": "接続、モデル、操作権限", "完成": "完了", "界面语言": "表示言語", "选择界面显示语言，修改后立即生效。": "表示言語を選択します。変更はすぐに反映されます。", "TokenHub 密钥已保存": "TokenHub キー保存済み", "连接 TokenHub": "TokenHub に接続", "粘贴 TokenHub sk-…": "TokenHub sk-… を貼り付け", "保存到钥匙串": "キーチェーンに保存", "文稿分析模型": "台本分析モデル", "模型 ID": "モデル ID", "交互权限": "操作権限", "启用中键双击 / 重新检查权限": "中ボタンのダブルクリックを有効化 / 再確認", "TokenHub 在线推理服务": "TokenHub オンライン推論", "保留可执行的恢复入口": "利用可能な復元ポイント", "还没有生成记录。": "生成履歴はありません。", "恢复时间线：": "タイムラインのバックアップ：", "显示文件": "ファイルを表示", "重新采用": "再利用", "选择空闲音轨": "空きオーディオトラックを選択", "使用": "使用", "取消": "キャンセル", "切换迷你控制窗": "ミニウインドウを切り替え",
            "换一版描述 · 本地随机，无需联网": "別の説明をローカルで生成", "换一版音乐描述": "別の音楽説明", "粘贴解说词、故事梗概或分镜，分析后转成配乐描述…": "ナレーション、あらすじ、ショットリストを貼り付けて音楽説明を作成…", "文字分析会发送至 TokenHub LLM，并按模型用量计费。": "テキスト分析は TokenHub LLM に送信され、モデル使用量に応じて課金されます。", "音乐按首计费。生成后裁切匹配选区，备选默认静音。": "音楽は1曲ごとに課金されます。選択範囲に合わせてトリミングし、別案は初期状態でミュートされます。", "填写 TokenHub 的 model 参数值（如 hy3 或 minimax-m3；不要填 minimax）。请单独开通该语言模型的按量服务。": "TokenHub の model 値（hy3、minimax-m3 など）を入力してください。minimax は使用しないでください。", "中键双击仅在 Resolve 前台生效。红色退出应用、黄色最小化、绿色或品牌标志切换迷你窗；迷你窗双击恢复完整界面。": "中ボタンのダブルクリックは Resolve が前面にあるときだけ動作します。赤は終了、黄は最小化、緑またはブランドマークはミニ表示を切り替えます。", "首次在 Resolve 中将主轨设为紫色、备选轨设为蓝色。语音输入使用设备端中文识别，点击麦克风时请求权限。": "Resolve でメイントラックを紫、別案を青に一度設定してください。音声入力はデバイス上の認識を使用します。", "A3/A4 不可用，或当前工作区位于其他轨道。将使用新的连续空轨。": "A3/A4 を使用できないため、新しい連続した空きトラックを使用します。", "为这一刻配乐。": "この瞬間に音楽を。", "打开 Resolve 时间线，开始创作。": "Resolve のタイムラインを開いて始めましょう。", "已连接": "接続済み", "密钥已保存到 macOS 钥匙串。": "キーを macOS キーチェーンに保存しました。",
            "雄壮升旗": "荘厳な式典", "温暖叙事": "温かな物語", "悬疑张力": "サスペンス", "科技律动": "テック・パルス", "史诗磅礴": "エピック", "清新自然": "爽やかな自然", "古风国韵": "中国古典", "轻快活力": "明るい活力", "沉静冥想": "静かな瞑想", "爵士都市": "アーバン・ジャズ"
        ],
        "ko": [
            "待机": "대기", "文字输入": "텍스트 입력", "语音输入": "음성 입력", "正在预检": "확인 중", "正在生成": "생성 중", "正在下载": "다운로드 중", "正在写入": "삽입 중", "生成完成": "완료", "任务失败": "실패", "已选择": "선택됨", "未选择": "선택 안 됨", "为这一刻配乐": "이 순간을 위한 음악", "正在聆听 · 再次点击麦克风结束": "듣는 중 · 마이크를 다시 눌러 종료", "未连接达芬奇": "Resolve 연결 안 됨", "已连接达芬奇": "Resolve 연결됨", "设置": "설정", "音乐时长": "음악 길이", "跟随 In-Out": "In-Out 따르기", "自定义": "사용자 지정", "秒": "초", "音乐时长滑杆": "음악 길이", "风格选择": "스타일", "随机风格": "무작위 스타일", "输入方式": "입력", "音乐描述": "음악 설명", "文稿配乐": "대본 음악", "结束输入": "입력 종료", "分析中…": "분석 중…", "分析文稿": "대본 분석", "优化描述": "설명 다듬기", "配乐描述 · 可编辑": "음악 설명 · 편집 가능", "历史与恢复": "기록 및 복구", "正在处理…": "처리 중…", "生成并放入时间线": "생성하여 타임라인에 추가", "1 首": "1곡", "恢复下载": "다운로드 재개", "插入已下载音频": "다운로드한 오디오 삽입", "未连接时间线": "타임라인 연결 안 됨", "读取最新时间线": "타임라인 새로고침", "请打开 Resolve 项目": "Resolve 프로젝트를 여세요", "目标轨道": "대상 트랙", "主版本": "메인", "备选": "대안", "放置位置": "배치 위치", "前 10 秒": "10초 전", "In-Out 起点": "In-Out 시작", "当前点": "재생 헤드", "后 10 秒": "10초 후", "定位": "이동", "采用备选": "대안 사용", "连接、模型与交互权限": "연결, 모델 및 상호작용 권한", "完成": "완료", "界面语言": "인터페이스 언어", "选择界面显示语言，修改后立即生效。": "표시 언어를 선택하세요. 변경 사항은 즉시 적용됩니다.", "TokenHub 密钥已保存": "TokenHub 키 저장됨", "连接 TokenHub": "TokenHub 연결", "粘贴 TokenHub sk-…": "TokenHub sk-… 붙여넣기", "保存到钥匙串": "키체인에 저장", "文稿分析模型": "대본 분석 모델", "模型 ID": "모델 ID", "交互权限": "상호작용 권한", "启用中键双击 / 重新检查权限": "가운데 버튼 더블 클릭 활성화 / 권한 재확인", "TokenHub 在线推理服务": "TokenHub 온라인 추론", "保留可执行的恢复入口": "사용 가능한 복구 지점", "还没有生成记录。": "생성 기록이 없습니다.", "恢复时间线：": "타임라인 백업: ", "显示文件": "파일 보기", "重新采用": "다시 사용", "选择空闲音轨": "빈 오디오 트랙 선택", "使用": "사용", "取消": "취소", "切换迷你控制窗": "미니 창 전환",
            "换一版描述 · 本地随机，无需联网": "로컬에서 다른 설명 만들기", "换一版音乐描述": "다른 음악 설명", "粘贴解说词、故事梗概或分镜，分析后转成配乐描述…": "내레이션, 줄거리 또는 샷 목록을 붙여 넣어 음악 설명 만들기…", "文字分析会发送至 TokenHub LLM，并按模型用量计费。": "텍스트 분석은 TokenHub LLM으로 전송되며 모델 사용량에 따라 요금이 부과됩니다.", "音乐按首计费。生成后裁切匹配选区，备选默认静音。": "음악은 트랙별로 과금됩니다. 선택 구간에 맞게 자르고 대안은 기본 음소거됩니다.", "填写 TokenHub 的 model 参数值（如 hy3 或 minimax-m3；不要填 minimax）。请单独开通该语言模型的按量服务。": "TokenHub model 값(예: hy3 또는 minimax-m3)을 입력하세요. minimax는 사용하지 마세요.", "中键双击仅在 Resolve 前台生效。红色退出应用、黄色最小化、绿色或品牌标志切换迷你窗；迷你窗双击恢复完整界面。": "가운데 버튼 더블 클릭은 Resolve가 전면일 때만 작동합니다. 빨강은 종료, 노랑은 최소화, 초록 또는 브랜드 표시는 미니 창을 전환합니다.", "首次在 Resolve 中将主轨设为紫色、备选轨设为蓝色。语音输入使用设备端中文识别，点击麦克风时请求权限。": "Resolve에서 메인 트랙을 보라색, 대안 트랙을 파란색으로 한 번 설정하세요. 음성 입력은 기기 내 인식을 사용합니다.", "A3/A4 不可用，或当前工作区位于其他轨道。将使用新的连续空轨。": "A3/A4를 사용할 수 없어 새 연속 빈 트랙을 사용합니다.", "为这一刻配乐。": "이 순간을 위한 음악.", "打开 Resolve 时间线，开始创作。": "Resolve 타임라인을 열고 시작하세요.", "已连接": "연결됨", "密钥已保存到 macOS 钥匙串。": "키가 macOS 키체인에 저장되었습니다.",
            "雄壮升旗": "장엄한 의식", "温暖叙事": "따뜻한 이야기", "悬疑张力": "서스펜스", "科技律动": "테크 펄스", "史诗磅礴": "에픽", "清新自然": "산뜻한 자연", "古风国韵": "중국 고전", "轻快活力": "밝은 에너지", "沉静冥想": "고요한 명상", "爵士都市": "어반 재즈"
        ],
        "es": [
            "待机": "En espera", "文字输入": "Entrada de texto", "语音输入": "Entrada de voz", "正在预检": "Comprobando", "正在生成": "Generando", "正在下载": "Descargando", "正在写入": "Insertando", "生成完成": "Completado", "任务失败": "Error", "已选择": "Seleccionado", "未选择": "No seleccionado", "为这一刻配乐": "Música para este momento", "正在聆听 · 再次点击麦克风结束": "Escuchando · pulsa de nuevo para terminar", "未连接达芬奇": "Resolve desconectado", "已连接达芬奇": "Resolve conectado", "设置": "Ajustes", "音乐时长": "Duración", "跟随 In-Out": "Seguir In-Out", "自定义": "Personalizada", "秒": "s", "音乐时长滑杆": "Duración musical", "风格选择": "Estilo", "随机风格": "Estilo aleatorio", "输入方式": "Entrada", "音乐描述": "Descripción", "文稿配乐": "Música para guion", "结束输入": "Detener entrada", "分析中…": "Analizando…", "分析文稿": "Analizar guion", "优化描述": "Mejorar descripción", "配乐描述 · 可编辑": "Descripción musical · editable", "历史与恢复": "Historial y recuperación", "正在处理…": "Procesando…", "生成并放入时间线": "Generar y añadir a la línea de tiempo", "1 首": "1 pista", "恢复下载": "Reanudar descarga", "插入已下载音频": "Insertar audio descargado", "未连接时间线": "Sin línea de tiempo", "读取最新时间线": "Actualizar línea de tiempo", "请打开 Resolve 项目": "Abre un proyecto de Resolve", "目标轨道": "Pista de destino", "主版本": "Principal", "备选": "Alternativa", "放置位置": "Posición", "前 10 秒": "10 s antes", "In-Out 起点": "Inicio In-Out", "当前点": "Cursor", "后 10 秒": "10 s después", "定位": "Localizar", "采用备选": "Usar alternativa", "连接、模型与交互权限": "Conexión, modelo y permisos", "完成": "Listo", "界面语言": "Idioma de la interfaz", "选择界面显示语言，修改后立即生效。": "Elige el idioma de la interfaz. El cambio se aplica al instante.", "TokenHub 密钥已保存": "Clave de TokenHub guardada", "连接 TokenHub": "Conectar TokenHub", "粘贴 TokenHub sk-…": "Pega TokenHub sk-…", "保存到钥匙串": "Guardar en Llavero", "文稿分析模型": "Modelo de análisis de guion", "模型 ID": "ID del modelo", "交互权限": "Permisos de interacción", "启用中键双击 / 重新检查权限": "Activar doble clic central / Revisar permisos", "TokenHub 在线推理服务": "Inferencia en línea de TokenHub", "保留可执行的恢复入口": "Recupera versiones anteriores", "还没有生成记录。": "Aún no hay historial.", "恢复时间线：": "Copia de la línea de tiempo: ", "显示文件": "Mostrar archivo", "重新采用": "Volver a usar", "选择空闲音轨": "Elegir pistas de audio libres", "使用": "Usar", "取消": "Cancelar", "切换迷你控制窗": "Alternar ventana compacta",
            "换一版描述 · 本地随机，无需联网": "Probar otra variación local", "换一版音乐描述": "Probar otra descripción", "粘贴解说词、故事梗概或分镜，分析后转成配乐描述…": "Pega una narración, sinopsis o lista de planos para crear una descripción musical…", "文字分析会发送至 TokenHub LLM，并按模型用量计费。": "El análisis de texto se envía al LLM de TokenHub y se factura según el uso.", "音乐按首计费。生成后裁切匹配选区，备选默认静音。": "La música se factura por pista. Se recorta al rango y la alternativa queda silenciada.", "填写 TokenHub 的 model 参数值（如 hy3 或 minimax-m3；不要填 minimax）。请单独开通该语言模型的按量服务。": "Introduce el valor model de TokenHub, como hy3 o minimax-m3; no uses minimax.", "中键双击仅在 Resolve 前台生效。红色退出应用、黄色最小化、绿色或品牌标志切换迷你窗；迷你窗双击恢复完整界面。": "El doble clic central solo funciona con Resolve en primer plano. Rojo cierra, amarillo minimiza y verde o el logotipo alternan la ventana compacta.", "首次在 Resolve 中将主轨设为紫色、备选轨设为蓝色。语音输入使用设备端中文识别，点击麦克风时请求权限。": "En Resolve, configura una vez la pista principal en violeta y la alternativa en azul. La voz usa reconocimiento del dispositivo.", "A3/A4 不可用，或当前工作区位于其他轨道。将使用新的连续空轨。": "A3/A4 no están disponibles; se usará un nuevo par consecutivo de pistas vacías.", "为这一刻配乐。": "Música para este momento.", "打开 Resolve 时间线，开始创作。": "Abre una línea de tiempo de Resolve para empezar.", "已连接": "Conectado", "密钥已保存到 macOS 钥匙串。": "La clave se guardó en el Llavero de macOS.",
            "雄壮升旗": "Ceremonial", "温暖叙事": "Narrativa cálida", "悬疑张力": "Suspense", "科技律动": "Pulso tecnológico", "史诗磅礴": "Épica", "清新自然": "Naturaleza fresca", "古风国韵": "Clásica china", "轻快活力": "Energía luminosa", "沉静冥想": "Meditación", "爵士都市": "Jazz urbano"
        ]
    ]
}
